In [22]:
# install pdfplumber
!pip install pdfplumber

Collecting pdfplumber
  Downloading pdfplumber-0.11.7-py3-none-any.whl.metadata (42 kB)
     ---------------------------------------- 0.0/42.8 kB ? eta -:--:--
     -------------------------------------- - 41.0/42.8 kB 1.9 MB/s eta 0:00:01
     -------------------------------------- 42.8/42.8 kB 691.8 kB/s eta 0:00:00
Collecting pdfminer.six==20250506 (from pdfplumber)
  Downloading pdfminer_six-20250506-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: Pillow>=9.1 in c:\users\micha\anaconda3\lib\site-packages (from pdfplumber) (10.3.0)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-4.30.0-py3-none-win_amd64.whl.metadata (48 kB)
     ---------------------------------------- 0.0/48.5 kB ? eta -:--:--
     ---------------------------------------- 48.5/48.5 kB 1.2 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in c:\users\micha\anaconda3\lib\site-packages (from pdfminer.six==20250506->pdfplumber) (2.0.4)
Requirement already satisfied: cryptography>=36.0.0 in c:\users\micha\anaconda3\lib\site-packages (from pdfminer.six==20250506->pdfplumber) (42.0.5)
Requirement already satisfied: cffi>=1.12 in c:\users\micha\anaconda3\lib\site-packages (from cryptography>=36.0.0->pdfminer.six==20250506->pdfplumber) (1.16.0)
Requirement already satisfied: pycparser in c:\users\micha\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20250506->pdfplumber) (2.21)
Downloading pdfplumber-0.11.7-py3-none-any.whl (60 kB)
   ---------------------------------------- 0.0/60.0 kB ? eta -:--:--
   ---------------------------------- ----- 51.2/60.0 kB ? eta -:--:--
   ---------------------------------------- 60.0/60.0 kB 803.0 kB/s eta 0:00:00
Downloading pdfminer_six-20250506-py3-none-any.whl (5.6 MB)
   ---------------------------------------- 0.0/5.6 MB ? eta -:--:--
   --- ------------------------------------ 0.5/5.6 MB 9.6 MB/s eta 0:00:01
   ----------- ---------------------------- 1.6/5.6 MB 16.6 MB/s eta 0:00:01
   ------------------------- -------------- 3.5/5.6 MB 25.2 MB/s eta 0:00:01
   ---------------------------------------  5.6/5.6 MB 32.8 MB/s eta 0:00:01
   ---------------------------------------- 5.6/5.6 MB 25.7 MB/s eta 0:00:00
Downloading pypdfium2-4.30.0-py3-none-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   ------------------------------- -------- 2.3/2.9 MB 73.7 MB/s eta 0:00:01
   ---------------------------------------  2.9/2.9 MB 61.2 MB/s eta 0:00:01
   ---------------------------------------- 2.9/2.9 MB 30.7 MB/s eta 0:00:00
Installing collected packages: pypdfium2, pdfminer.six, pdfplumber
Successfully installed pdfminer.six-20250506 pdfplumber-0.11.7 pypdfium2-4.30.0

In [55]:
#Load Chargin Station Data
import pandas as pd
import os
import glob
import pdfplumber 
import re
import matplotlib.pyplot as plt
file_path = r"C:\Users\micha\OneDrive\Desktop\MSDS 420\Group Project\Charging Dataset\Electric and Alternative Fuel Charging Stations.csv"

# Load the dataset
df = pd.read_csv(file_path)
il_df = df[df['State'] == 'IL']


#Columns to Drop as they are completely empty or nearly empty 
cols_to_drop = [
    'Plus4', 'BD Blends', 'NG Fill Type Code', 'NG PSI',
    'Expected Date', 'Cards Accepted', 'EV Other Info',
    'Federal Agency ID', 'Federal Agency Name',
    'Hydrogen Status Link', 'NG Vehicle Class', 'LPG Primary',
    'E85 Blender Pump', 'Intersection Directions (French)',
    'Access Days Time (French)', 'BD Blends (French)',
    'Groups With Access Code (French)', 'Hydrogen Is Retail',
    'Federal Agency Code', 'CNG Dispenser Num', 'CNG On-Site Renewable Source',
    'CNG Total Compression Capacity', 'CNG Storage Capacity',
    'LNG On-Site Renewable Source', 'E85 Other Ethanol Blends',
    'EV Pricing (French)', 'LPG Nozzle Types', 'Hydrogen Pressures',
    'Hydrogen Standards', 'CNG Fill Type Code', 'CNG PSI',
    'CNG Vehicle Class', 'LNG Vehicle Class', 'EV On-Site Renewable Source'
]

# Drop columns from your Illinois EV dataset
il_df = il_df.drop(columns=cols_to_drop, errors = 'ignore')
il_df.head()

C:\Users\micha\AppData\Local\Temp\ipykernel_11216\4019769242.py:11: DtypeWarning: Columns (6,16,20,31,33,36,39,40,41,43,46,52,53,55,57,58,60,62) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

,Fuel Type Code,Station Name,Street Address,Intersection Directions,City,State,ZIP,Station Phone,Status Code,Groups With Access Code,...,Updated At,Owner Type Code,Open Date,EV Connector Types,Country,Access Code,Access Detail Code,Facility Type,EV Pricing,Restricted Access
185,E85,Phillips 66 - Sandy's,4545 Sandy Hollow Rd,At S Alpine,Rockford,IL,61109,815-874-2214,E,Public,...,2021-11-18 21:49:42 UTC,P,2019-08-30,NaN,US,public,NaN,CONVENIENCE_STORE,NaN,False
258,LPG,Thompson Gas,1431 N Illinois St,"3 blocks south of Route 161 and Route 159, or ...",Swansea,IL,62226,618-233-6541,E,Public,...,2022-02-22 17:20:35 UTC,P,1999-07-08,NaN,US,public,NaN,FUEL_RESELLER,NaN,False
305,LPG,Ferrellgas,10522 N 2nd St,North of 173 on 251,Machesney Park,IL,61115,815-877-7333,E,Public,...,2022-02-10 19:42:29 UTC,P,1999-07-08,NaN,US,public,NaN,FUEL_RESELLER,NaN,False
359,CNG,Gas Technology Institute,1700 S Mount Prospect Rd,"0.5 mile north of Touhy Ave, just north of O'H...",Des Plaines,IL,60018,847-768-0500,E,Public - Credit card at all times,...,2022-02-10 19:42:29 UTC,P,1995-01-15,NaN,US,public,CREDIT_CARD_ALWAYS,STANDALONE_STATION,NaN,False
483,LPG,U-Haul,1560 Mount Prospect Rd,"Corner of Oakton and Mt. Prospect, between 83 ...",Des Plaines,IL,60018,847-298-1170,E,Public,...,2022-02-22 14:31:10 UTC,P,2000-11-01,NaN,US,public,NaN,RENTAL_CAR_RETURN,NaN,False

In [57]:
# Fill NA with 0 for charger counts
for col in ['EV Level1 EVSE Num', 'EV Level2 EVSE Num', 'EV DC Fast Count']:
    il_df[col] = il_df[col].fillna(0)

# Create total chargers column
il_df['Total Chargers'] = (
    il_df['EV Level1 EVSE Num'] +
    il_df['EV Level2 EVSE Num'] +
    il_df['EV DC Fast Count']
)

# Check new shape and preview
print(il_df.shape)
il_df[['Station Name', 'City', 'ZIP', 'Total Chargers']].head()
il_df['Total Chargers'].value_counts().sort_index()

(1636, 32)

Total Chargers
0.0     522
1.0     278
2.0     624
3.0      51
4.0      64
5.0       7
6.0      28
7.0       1
8.0      28
10.0     10
11.0      2
12.0      8
14.0      3
16.0      3
20.0      1
22.0      1
24.0      3
26.0      1
31.0      1
Name: count, dtype: int64

In [59]:
ev_df = il_df[il_df['Fuel Type Code'] == 'ELEC']
ev_df['Total Chargers'].value_counts().sort_index()

Total Chargers
1.0     278
2.0     624
3.0      51
4.0      64
5.0       7
6.0      28
7.0       1
8.0      28
10.0     10
11.0      2
12.0      8
14.0      3
16.0      3
20.0      1
22.0      1
24.0      3
26.0      1
31.0      1
Name: count, dtype: int64

In [61]:
#Load Demographic Data
# Setup
import requests
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# For geospatial mapping
#import geopandas as gpd
#from shapely.geometry import Point
# ==============================
# CONFIG
# ==============================
API_KEY = "0b0513fe67b0e2da1250859200feb24c65be5558"
STATE_FIPS = "17"  # Illinois
YEARS = ["2021", "2022", "2023"]

# Variables (counts only) - Added Total Population
VARIABLES_COUNTS = [
    # Total Population
    "DP05_0001E",
    # Income
    "DP03_0062E","DP03_0052E","DP03_0053E","DP03_0054E","DP03_0055E",
    "DP03_0056E","DP03_0057E","DP03_0058E","DP03_0059E","DP03_0060E",
    "DP03_0061E",
    # Age
    "DP02_0014E","DP02_0015E","DP02_0016E","DP02_0017E","DP02_0018E",
    "DP02_0019E","DP02_0020E","DP02_0021E","DP02_0022E","DP02_0023E",
    "DP02_0024E","DP02_0025E","DP02_0026E",
    # Education
    "DP02_0062E","DP02_0063E","DP02_0064E","DP02_0065E","DP02_0066E",
    "DP02_0067E","DP02_0068E",
    # Race/Ethnicity
    "DP05_0037E","DP05_0038E","DP05_0039E","DP05_0044E","DP05_0052E",
    "DP05_0057E","DP05_0058E","DP05_0071E","DP05_0072E"
]

# Human-readable mapping for major variables
COL_RENAME = {
    "NAME": "Geography",
    "DP05_0001E": "Total_Population",
    "DP03_0062E": "Median_HH_Income",
    "DP03_0052E": "HH_Income_<10k",
    "DP03_0053E": "HH_Income_10k_14k",
    "DP03_0054E": "HH_Income_15k_24k",
    "DP03_0055E": "HH_Income_25k_34k",
    "DP03_0056E": "HH_Income_35k_49k",
    "DP03_0057E": "HH_Income_50k_74k",
    "DP03_0058E": "HH_Income_75k_99k",
    "DP03_0059E": "HH_Income_100k_149k",
    "DP03_0060E": "HH_Income_150k_199k",
    "DP03_0061E": "HH_Income_200k_plus",
    "DP02_0014E": "Age_Under_5",
    "DP02_0015E": "Age_5_9",
    "DP02_0016E": "Age_10_14",
    "DP02_0017E": "Age_15_19",
    "DP02_0018E": "Age_20_24",
    "DP02_0019E": "Age_25_34",
    "DP02_0020E": "Age_35_44",
    "DP02_0021E": "Age_45_54",
    "DP02_0022E": "Age_55_59",
    "DP02_0023E": "Age_60_64",
    "DP02_0024E": "Age_65_74",
    "DP02_0025E": "Age_75_84",
    "DP02_0026E": "Age_85_plus",
    "DP02_0062E": "Edu_Less_9th",
    "DP02_0063E": "Edu_9_12_NoDiploma",
    "DP02_0064E": "Edu_HS_Grad",
    "DP02_0065E": "Edu_SomeCollege",
    "DP02_0066E": "Edu_Associate",
    "DP02_0067E": "Edu_Bachelors",
    "DP02_0068E": "Edu_Graduate",
    "DP05_0037E": "Race_White",
    "DP05_0038E": "Race_Black",
    "DP05_0039E": "Race_AmericanIndian",
    "DP05_0044E": "Race_Asian",
    "DP05_0052E": "Race_NativeHawaiian",
    "DP05_0057E": "Race_Other",
    "DP05_0058E": "Race_TwoOrMore",
    "DP05_0071E": "Ethn_Hispanic",
    "DP05_0072E": "Ethn_NonHispanic"
}

# ==============================
# MULTI-YEAR DATA PULL
# ==============================
county_all = []
zip_all = []

for yr in YEARS:
    print(f"Pulling data for {yr}...")

    base_url = f"https://api.census.gov/data/{yr}/acs/acs5/profile"

    # ---- COUNTY DATA ----
    params_county = {
        "get": ",".join(["NAME"] + VARIABLES_COUNTS),
        "for": "county:*",
        "in": f"state:{STATE_FIPS}",
        "key": API_KEY
    }
    resp = requests.get(base_url, params=params_county)
    resp.raise_for_status()
    data = resp.json()
    df_county = pd.DataFrame(columns=data[0], data=data[1:])
    df_county.rename(columns=lambda x: COL_RENAME.get(x, x), inplace=True)
    df_county["Year"] = yr
    county_all.append(df_county)

    # ---- zip DATA ----
    params_zip = {
        "get": ",".join(["NAME"] + VARIABLES_COUNTS),
        "for": "zip code tabulation area:*",
        "key": API_KEY
    }
    resp = requests.get(base_url, params=params_zip)
    resp.raise_for_status()
    data = resp.json()
    df_zip = pd.DataFrame(columns=data[0], data=data[1:])
    df_zip.rename(columns=lambda x: COL_RENAME.get(x, x), inplace=True)
    df_zip["Year"] = yr

    # Illinois ZIP filter (prefix method: 60xxx, 61xxx, 62xxx)
    df_zip = df_zip[df_zip['zip code tabulation area'].str.startswith(('60', '61', '62'))]

    zip_all.append(df_zip)

# Combine all years
county_df = pd.concat(county_all, ignore_index=True)
zip_df = pd.concat(zip_all, ignore_index=True)

print("✅ Pull complete:")
print("  County DF shape:", county_df.shape)
print("  Zip DF shape:", zip_df.shape)

# ==============================
# SAVE FINAL COMBINED CSVs
# ==============================
county_df.to_csv("il_census_county_counts_2021_2023.csv", index=False)
zip_df.to_csv("il_census_zcta_counts_2021_2023.csv", index=False)

print("✅ Multi-year combined files saved successfully.")

Pulling data for 2021...
Pulling data for 2022...
Pulling data for 2023...
✅ Pull complete:
  County DF shape: (306, 45)
  Zip DF shape: (4188, 44)
✅ Multi-year combined files saved successfully.

In [83]:
# Load your saved data
county_demo_df = pd.read_csv("il_census_county_counts_2021_2023.csv", dtype=str)
zip_demo_df = pd.read_csv("il_census_zcta_counts_2021_2023.csv", dtype=str)
county_demo_df.head()
county_demo_df.shape

(306, 45)

In [81]:

zip_demo_df.head()
zip_demo_df.shape

(4188, 44)

In [29]:
# Load EV Counts by County and zip
#####  Counts by County and City Database #####
!git clone https://github.com/ayaghmour2/Database-Systems-EV-Project.git

## Change working directory
import os, glob, time, sys, re, pandas as pd, pdfplumber
os.chdir("Database-Systems-EV-Project/Data")

## Grab all files with 'electric' in the file name
pdf_files = sorted(glob.glob("electric*.pdf"))
print(f"{len(pdf_files)} PDFs found")

## Extract County and Zip Code
county_rows, zip_rows = [], []

start = time.time()

for i, pdf_file in enumerate(pdf_files, start=1):
    with pdfplumber.open(pdf_file) as pdf:
        text = ""
        for page in pdf.pages:
            t = page.extract_text() or ""
            text += t + "\n"

    # Extract date from header
    date_match = re.search(r"AS OF (\d{2}/\d{2}/\d{4})", text)
    date = pd.to_datetime(date_match.group(1)) if date_match else None

    # County table extraction
    county_section = re.search(
        r"COUNTY TOTALS AS OF.*?\n(.*?)(?:ELECTRIC VEHICLES IN ILLINOIS ZIPCODE TOTALS|ELECTRIC VEHICLES IN ILLINOIS\\nZIPCODE TOTALS|ZIPCODE TOTALS AS OF)",
        text, re.DOTALL
    )
    if county_section:
        for line in county_section.group(1).split("\n"):
            match = re.match(r"([A-Z .'-]+?)\s*\.*\s+([0-9]+)", line.strip())
            if match:
                county, count = match.groups()
                county_rows.append({
                    "Date": date,
                    "County": county.strip(),
                    "Count": int(count),
                    "Source File": pdf_file
                })

    # Zip code table extraction
    zip_section = re.search(r"ZIPCODE TOTALS AS OF.*?\n(.*)", text, re.DOTALL)
    if zip_section:
        for line in zip_section.group(1).split("\n"):
            match = re.match(r"([A-Z .'-]+)\s+(\d{5})\s+([0-9]+)", line.strip())
            if match:
                city, zipcode, count = match.groups()
                zip_rows.append({
                    "Date": date,
                    "City": city.strip(),
                    "ZIP Code": zipcode,
                    "Count": int(count),
                    "Source File": pdf_file
                })

    # Progress print
    print(f"Finished {i}/{len(pdf_files)}: {pdf_file}")
    sys.stdout.flush()

elapsed = time.time() - start
print(f"\nAll done in {elapsed:.2f} seconds")

# Convert to DataFrames for downstream work (optional but handy)
county_df = pd.DataFrame(county_rows)
zip_df    = pd.DataFrame(zip_rows)

print("county_df:", county_df.shape, "zip_df:", zip_df.shape)

Cloning into 'Database-Systems-EV-Project'...

47 PDFs found
Finished 1/47: electric011522.pdf
Finished 2/47: electric011523.pdf
Finished 3/47: electric011524.pdf
Finished 4/47: electric011525.pdf
Finished 5/47: electric021522.pdf
Finished 6/47: electric021524.pdf
Finished 7/47: electric021525.pdf
Finished 8/47: electric022723.pdf
Finished 9/47: electric031522.pdf
Finished 10/47: electric031523.pdf
Finished 11/47: electric031524.pdf
Finished 12/47: electric031525.pdf
Finished 13/47: electric041522.pdf
Finished 14/47: electric041523.pdf
Finished 15/47: electric041524.pdf
Finished 16/47: electric041525.pdf
Finished 17/47: electric051522.pdf
Finished 18/47: electric051523.pdf
Finished 19/47: electric051524.pdf
Finished 20/47: electric051525.pdf
Finished 21/47: electric061522.pdf
Finished 22/47: electric061523.pdf
Finished 23/47: electric061524.pdf
Finished 24/47: electric061525.pdf
Finished 25/47: electric071522.pdf
Finished 26/47: electric071523.pdf
Finished 27/47: electric071524.pdf
Finished 28/47: electric071525.pdf
Finished 29/47: electric081522.pdf
Finished 30/47: electric081523.pdf
Finished 31/47: electric081524.pdf
Finished 32/47: electric091521.pdf
Finished 33/47: electric091522.pdf
Finished 34/47: electric091523.pdf
Finished 35/47: electric091524.pdf
Finished 36/47: electric101521.pdf
Finished 37/47: electric101522.pdf
Finished 38/47: electric101523.pdf
Finished 39/47: electric101524.pdf
Finished 40/47: electric111521.pdf
Finished 41/47: electric111522.pdf
Finished 42/47: electric111523.pdf
Finished 43/47: electric111524.pdf
Finished 44/47: electric121521.pdf
Finished 45/47: electric121522.pdf
Finished 46/47: electric121523.pdf
Finished 47/47: electric121524.pdf

All done in 562.26 seconds
county_df: (4888, 4) zip_df: (75230, 5)

In [69]:
## Create pandas dataframes for analysis
county_registration_df = pd.DataFrame(county_rows)
zipcode_registration_df = pd.DataFrame(zip_rows)

## Data type for each dataframe
print(county_registration_df.info())
print(zipcode_registration_df.info())
zipcode_registration_df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         4888 non-null   datetime64[ns]
 1   County       4888 non-null   object
 2   Count        4888 non-null   int64
 3   Source File  4888 non-null   object
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 152.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75230 entries, 0 to 75229
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         75230 non-null  datetime64[ns]
 1   City         75230 non-null  object
 2   ZIP Code     75230 non-null  object
 3   Count        75230 non-null  int64
 4   Source File  75230 non-null  object
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 2.9+ MB
None

Index(['Date', 'City', 'ZIP Code', 'Count', 'Source File'], dtype='object')

In [1]:
from sqlalchemy import create_engine
import pandas as pd

# connect to your local postgres db
engine = create_engine("postgresql+psycopg2://postgres:sql@localhost:5432/ev_project", future=True)

In [41]:
# charging stations
il_df.to_sql("il_df", engine, index=False, if_exists="replace")

# county registration
county_registration_df.to_sql("county_registration_df", engine, index=False, if_exists="replace")

# zipcode registration
zipcode_registration_df.to_sql("zipcode_registration_df", engine, index=False, if_exists="replace")

230

In [73]:
# zip demographics
zip_demo_df.to_sql("zip_demo_df", engine, index=False, if_exists="replace")

# county demographics
county_demo_df.to_sql("county_demo_df", engine, index=False, if_exists="replace")

306

In [5]:
#ANLYSIS Starts Here
import psycopg2
import pandas as pd

# --- connect to your DB ---
conn = psycopg2.connect(
    host="localhost",   # or your host
    port="5432",
    database="ev_project",
    user="postgres",
    password="sql"
)

# --- helper to pull entire table into DataFrame ---
def load_table(table_name):
    return pd.read_sql(f"SELECT * FROM {table_name}", conn)

# --- load each table ---
county_demo = load_table("county_demo_df")
county_reg = load_table("county_registration_df")
zip_demo = load_table("zip_demo_df")
zip_reg = load_table("zipcode_registration_df")
stations = load_table("il_df")

# --- preview ---
print(county_demo.head())
print(stations.head())
stations.head()

C:\Users\micha\AppData\Local\Temp\ipykernel_18168\702387337.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(f"SELECT * FROM {table_name}", conn)

                    geography total_population median_hh_income  \
0      Adams County, Illinois            65878            58587
1  Alexander County, Illinois             5488            39871
2       Bond County, Illinois            16804            53654
3      Boone County, Illinois            53592            74076
4      Brown County, Illinois             6330            59346

  hh_income_lt_10k hh_income_10k_14k hh_income_15k_24k hh_income_25k_34k  \
0             1375               923              2714              2631
1              175               152               273               226
2              503               261               596               519
3              674               570              1252              1663
4               46               141               215               109

  hh_income_35k_49k hh_income_50k_74k hh_income_75k_99k  ...  \
0              3889              5213              3941  ...
1               298               307               162  ...
2               940              1119               801  ...
3              2071              3353              2592  ...
4               358               410               271  ...

  race_american_indian race_asian race_native_hawaiian race_other  \
0                   51        420                    8        153
1                    4          1                   22          0
2                  112        165                    0         36
3                  160        523                    0       4200
4                   39          3                    0        135

  race_two_or_more ethn_hispanic ethn_non_hispanic state county  year
0             1942          1146               637    17    001  2021
1              123            62                37    17    003  2021
2              187           630               403    17    005  2021
3             2377         12223             10974    17    007  2021
4              103           436               337    17    009  2021

[5 rows x 45 columns]
  fuel_type_code              station_name            street_address  \
0            E85     Phillips 66 - Sandy's      4545 Sandy Hollow Rd
1            LPG              Thompson Gas        1431 N Illinois St
2            LPG                Ferrellgas            10522 N 2nd St
3            CNG  Gas Technology Institute  1700 S Mount Prospect Rd
4            LPG                    U-Haul    1560 Mount Prospect Rd

                             intersection_directions            city state  \
0                                        At S Alpine        Rockford    IL
1  3 blocks south of Route 161 and Route 159, or ...         Swansea    IL
2                                North of 173 on 251  Machesney Park    IL
3  0.5 mile north of Touhy Ave, just north of O'H...     Des Plaines    IL
4  Corner of Oakton and Mt. Prospect, between 83 ...     Des Plaines    IL

  zipcode station_phone status_code            groups_with_access_code  ...  \
0   61109  815-874-2214           E                             Public  ...
1   62226  618-233-6541           E                             Public  ...
2   61115  815-877-7333           E                             Public  ...
3   60018  847-768-0500           E  Public - Credit card at all times  ...
4   60018  847-298-1170           E                             Public  ...

                updated_at  owner_type_code   open_date  ev_connector_types  \
0  2021-11-18 21:49:42 UTC                P  2019-08-30                None
1  2022-02-22 17:20:35 UTC                P  1999-07-08                None
2  2022-02-10 19:42:29 UTC                P  1999-07-08                None
3  2022-02-10 19:42:29 UTC                P  1995-01-15                None
4  2022-02-22 14:31:10 UTC                P  2000-11-01                None

  country access_code  access_detail_code       facility_type  ev_pricing  \
0      US      public                None   CONVENIENCE_STORE        None
1      US      public                None       FUEL_RESELLER        None
2      US      public                None       FUEL_RESELLER        None
3      US      public  CREDIT_CARD_ALWAYS  STANDALONE_STATION        None
4      US      public                None   RENTAL_CAR_RETURN        None

  restricted_access
0             False
1             False
2             False
3             False
4             False

[5 rows x 31 columns]

,fuel_type_code,station_name,street_address,intersection_directions,city,state,zipcode,station_phone,status_code,groups_with_access_code,...,updated_at,owner_type_code,open_date,ev_connector_types,country,access_code,access_detail_code,facility_type,ev_pricing,restricted_access
0,E85,Phillips 66 - Sandy's,4545 Sandy Hollow Rd,At S Alpine,Rockford,IL,61109,815-874-2214,E,Public,...,2021-11-18 21:49:42 UTC,P,2019-08-30,None,US,public,None,CONVENIENCE_STORE,None,False
1,LPG,Thompson Gas,1431 N Illinois St,"3 blocks south of Route 161 and Route 159, or ...",Swansea,IL,62226,618-233-6541,E,Public,...,2022-02-22 17:20:35 UTC,P,1999-07-08,None,US,public,None,FUEL_RESELLER,None,False
2,LPG,Ferrellgas,10522 N 2nd St,North of 173 on 251,Machesney Park,IL,61115,815-877-7333,E,Public,...,2022-02-10 19:42:29 UTC,P,1999-07-08,None,US,public,None,FUEL_RESELLER,None,False
3,CNG,Gas Technology Institute,1700 S Mount Prospect Rd,"0.5 mile north of Touhy Ave, just north of O'H...",Des Plaines,IL,60018,847-768-0500,E,Public - Credit card at all times,...,2022-02-10 19:42:29 UTC,P,1995-01-15,None,US,public,CREDIT_CARD_ALWAYS,STANDALONE_STATION,None,False
4,LPG,U-Haul,1560 Mount Prospect Rd,"Corner of Oakton and Mt. Prospect, between 83 ...",Des Plaines,IL,60018,847-298-1170,E,Public,...,2022-02-22 14:31:10 UTC,P,2000-11-01,None,US,public,None,RENTAL_CAR_RETURN,None,False

In [29]:
stations = stations[stations["access_code"]=="public"]
stations['status_code'].value_counts()

status_code
E    1476
T       2
P       2
Name: count, dtype: int64

In [23]:
import pandas as pd
import numpy as np

# Use your filtered stations df here
# If you named it differently, just replace 'stations_public' below.
stations_df = stations.copy()

# --- Normalize ZIPs to 5-char strings ---
def to_5zip(z):
    if pd.isna(z): 
        return None
    s = str(z).strip()
    # keep only digits, pad to 5
    digits = "".join(ch for ch in s if ch.isdigit())
    return digits.zfill(5) if digits else None

stations_df["zipcode"] = stations_df["zipcode"].apply(to_5zip)
zip_reg["zipcode"] = zip_reg["zipcode"].apply(to_5zip)

# --- Aggregate station + port supply by ZIP ---
stations_zip = (
    stations_df
      .groupby("zipcode", dropna=False)
      .agg(
          station_count=("id", "count"),                    # or "station_name" if preferred
          level2_ports=("ev_level2_evse_num", "sum"),
          dc_fast_ports=("ev_dc_fast_count", "sum")
      )
      .fillna(0)
      .reset_index()
)

stations_zip["total_ports"] = stations_zip["level2_ports"].fillna(0) + stations_zip["dc_fast_ports"].fillna(0)

# --- Latest registration per ZIP ---
zip_reg["date"] = pd.to_datetime(zip_reg["date"], errors="coerce")
latest_reg = (
    zip_reg.sort_values(["zipcode","date"])
           .groupby("zipcode", as_index=False)
           .tail(1)[["zipcode","city","registration_count","date"]]
           .rename(columns={"date":"reg_asof"})
)

# --- Join and compute demand ratios ---
zip_metrics = (
    latest_reg.merge(stations_zip, on="zipcode", how="left")
              .fillna({"station_count":0, "level2_ports":0, "dc_fast_ports":0, "total_ports":0})
)

zip_metrics["ev_per_station"] = np.where(
    zip_metrics["station_count"] > 0,
    zip_metrics["registration_count"] / zip_metrics["station_count"],
    np.nan
)

zip_metrics["ev_per_port"] = np.where(
    zip_metrics["total_ports"] > 0,
    zip_metrics["registration_count"] / zip_metrics["total_ports"],
    np.nan
)

# --- Peek results ---
print(zip_metrics.shape)
print(
    zip_metrics.head(10)[
        ["zipcode","city","registration_count","station_count","total_ports","ev_per_station","ev_per_port","reg_asof"]
    ]
)

(1601, 10)
  zipcode               city  registration_count  station_count  total_ports  \
0   60001              ALDEN                   0            0.0          0.0
1   60002            ANTIOCH                 239            1.0          2.0
2   60004  ARLINGTON HEIGHTS                1150            4.0          8.0
3   60005  ARLINGTON HEIGHTS                 564            4.0          6.0
4   60006  ARLINGTON HEIGHTS                   1            0.0          0.0
5   60007  ELK GROVE VILLAGE                 571            6.0         11.0
6   60008    ROLLING MEADOWS                 398            5.0         30.0
7   60009  ELK GROVE VILLAGE                   0            0.0          0.0
8   60010         BARRINGTON                2011           22.0         32.0
9   60011         BARRINGTON                   1            0.0          0.0

   ev_per_station  ev_per_port   reg_asof
0             NaN          NaN 2025-07-15
1      239.000000   119.500000 2025-07-15
2      287.500000   143.750000 2025-07-15
3      141.000000    94.000000 2025-07-15
4             NaN          NaN 2025-07-15
5       95.166667    51.909091 2025-07-15
6       79.600000    13.266667 2025-07-15
7             NaN          NaN 2025-07-15
8       91.409091    62.843750 2025-07-15
9             NaN          NaN 2025-07-15

In [25]:
zero_supply = zip_metrics[(zip_metrics["registration_count"] > 0) & (zip_metrics["total_ports"] == 0)]
print("ZIPs with EVs but zero public ports:", zero_supply.shape[0])
print(zero_supply[["zipcode","city","registration_count"]].head(15))

ZIPs with EVs but zero public ports: 883
   zipcode               city  registration_count
4    60006  ARLINGTON HEIGHTS                   1
9    60011         BARRINGTON                   1
11   60013               CARY                 330
19   60021    FOX RIVER GROVE                  83
22   60026           GLENVIEW                 645
23   60029               GOLF                  27
27   60034             HEBRON                  14
32   60040           HIGHWOOD                  68
33   60041          INGLESIDE                  52
34   60042        ISLAND LAKE                  57
35   60043         KENILWORTH                 143
36   60044         LAKE BLUFF                 355
44   60052            METTAWA                   1
46   60055           PALATINE                   2
48   60057     MOUNT PROSPECT                   1

In [27]:
import pandas as pd

sql_zip_reg_latest = """
WITH ranked AS (
  SELECT
    LPAD(TRIM(CAST(zipcode AS TEXT)), 5, '0') AS zipcode,
    city,
    registration_count,
    (date)::date AS reg_asof,
    ROW_NUMBER() OVER (
      PARTITION BY LPAD(TRIM(CAST(zipcode AS TEXT)), 5, '0')
      ORDER BY (date)::date DESC
    ) AS rn
  FROM zipcode_registration_df
)
SELECT zipcode, city, registration_count, reg_asof
FROM ranked
WHERE rn = 1
ORDER BY zipcode;
"""

zip_reg_latest = pd.read_sql(sql_zip_reg_latest, conn)
print(zip_reg_latest.shape)
print(zip_reg_latest.head(10))

C:\Users\micha\AppData\Local\Temp\ipykernel_18168\2953128983.py:22: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  zip_reg_latest = pd.read_sql(sql_zip_reg_latest, conn)

(1601, 4)
  zipcode               city  registration_count    reg_asof
0   60001              ALDEN                   0  2025-07-15
1   60002            ANTIOCH                 239  2025-07-15
2   60004  ARLINGTON HEIGHTS                1150  2025-07-15
3   60005  ARLINGTON HEIGHTS                 564  2025-07-15
4   60006  ARLINGTON HEIGHTS                   1  2025-07-15
5   60007  ELK GROVE VILLAGE                 571  2025-07-15
6   60008    ROLLING MEADOWS                 398  2025-07-15
7   60009  ELK GROVE VILLAGE                   0  2025-07-15
8   60010         BARRINGTON                2011  2025-07-15
9   60011         BARRINGTON                   1  2025-07-15

In [31]:
sql_stations_zip = """
SELECT
  LPAD(TRIM(CAST(zipcode AS TEXT)), 5, '0') AS zipcode,
  COUNT(*)                                   AS station_count,
  SUM(COALESCE(ev_level2_evse_num, 0))       AS level2_ports,
  SUM(COALESCE(ev_dc_fast_count, 0))         AS dc_fast_ports,
  SUM(COALESCE(ev_level2_evse_num, 0)) 
    + SUM(COALESCE(ev_dc_fast_count, 0))     AS total_ports
FROM il_df
WHERE status_code = 'E'
  AND (
        LOWER(COALESCE(access_code,'')) = 'public'
     OR LOWER(COALESCE(groups_with_access_code,'')) LIKE '%public%'
     OR LOWER(COALESCE(restricted_access::text,'')) = 'false'
  )
GROUP BY LPAD(TRIM(CAST(zipcode AS TEXT)), 5, '0')
ORDER BY zipcode;
"""

stations_zip = pd.read_sql(sql_stations_zip, conn)
print(stations_zip.shape)
print(stations_zip.head(10))

(437, 5)
  zipcode  station_count  level2_ports  dc_fast_ports  total_ports
0   60002              1           2.0            0.0          2.0
1   60004              4           5.0            3.0          8.0
2   60005              4           6.0            0.0          6.0
3   60007              6          11.0            0.0         11.0
4   60008              5           8.0           22.0         30.0
5   60010             22          28.0            4.0         32.0
6   60012              2           6.0            0.0          6.0
7   60013              2           0.0            0.0          0.0
8   60014              7           3.0            0.0          3.0
9   60015              3          12.0            0.0         12.0

C:\Users\micha\AppData\Local\Temp\ipykernel_18168\3240534115.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  stations_zip = pd.read_sql(sql_stations_zip, conn)

In [95]:
###This gives us first analysis table:

#latest EV registrations

#station/port supply

#ratios showing where demand pressure is highest

sql_zip_metrics = """  WITH reg_latest AS (
  SELECT
    LPAD(TRIM(CAST(zipcode AS TEXT)), 5, '0') AS zipcode,
    city,
    registration_count,
    (date)::date AS reg_asof,
    ROW_NUMBER() OVER (
      PARTITION BY LPAD(TRIM(CAST(zipcode AS TEXT)), 5, '0')
      ORDER BY (date)::date DESC
    ) AS rn
  FROM zipcode_registration_df
),
zip_reg AS (
  SELECT zipcode, city, registration_count, reg_asof
  FROM reg_latest
  WHERE rn = 1
),
stations_zip AS (
  SELECT
    LPAD(TRIM(CAST(zipcode AS TEXT)), 5, '0') AS zipcode,
    COUNT(*)                             AS station_count,
    SUM(COALESCE(ev_level2_evse_num,0))  AS level2_ports,
    SUM(COALESCE(ev_dc_fast_count,0))    AS dc_fast_ports,
    SUM(COALESCE(ev_level2_evse_num,0)) 
      + SUM(COALESCE(ev_dc_fast_count,0)) AS total_ports
  FROM il_df
  WHERE status_code = 'E'
    AND (
          LOWER(COALESCE(access_code,'')) = 'public'
       OR LOWER(COALESCE(groups_with_access_code,'')) LIKE '%public%'
       OR LOWER(COALESCE(restricted_access::text,'')) = 'false'
    )
  GROUP BY LPAD(TRIM(CAST(zipcode AS TEXT)), 5, '0')
)
SELECT
  r.zipcode,
  r.city,
  r.registration_count,
  r.reg_asof,
  COALESCE(s.station_count,0)   AS station_count,
  COALESCE(s.level2_ports,0)    AS level2_ports,
  COALESCE(s.dc_fast_ports,0)   AS dc_fast_ports,
  COALESCE(s.total_ports,0)     AS total_ports,
  CASE WHEN s.station_count > 0
       THEN ROUND(r.registration_count::numeric / s.station_count,2)
       ELSE NULL END AS ev_per_station,
  CASE WHEN s.total_ports > 0
       THEN r.registration_count::numeric / s.total_ports
       ELSE NULL END AS ev_per_port
FROM zip_reg r
LEFT JOIN stations_zip s USING (zipcode)
ORDER BY ev_per_port DESC NULLS LAST;
 """

zip_metrics = pd.read_sql(sql_zip_metrics, conn)

# quick look
print(zip_metrics.shape)
print(zip_metrics.head(10))

# see top underserved (high EVs per port)
underserved = zip_metrics.sort_values("ev_per_port", ascending=False)
display(underserved.head(20)[
    ["zipcode","city","registration_count","station_count","total_ports","ev_per_port"]
])

C:\Users\micha\AppData\Local\Temp\ipykernel_18168\2396217627.py:63: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  zip_metrics = pd.read_sql(sql_zip_metrics, conn)

(1601, 10)
  zipcode             city  registration_count    reg_asof  station_count  level2_ports  dc_fast_ports  total_ports  ev_per_station  ev_per_port
0   60622          CHICAGO                1022  2025-07-15              1           1.0            0.0          1.0          1022.0       1022.0
1   60565       NAPERVILLE                1307  2025-07-15              1           2.0            0.0          2.0          1307.0        653.5
2   60630          CHICAGO                 550  2025-07-15              1           1.0            0.0          1.0           550.0        550.0
3   60521         HINSDALE                1023  2025-07-15              2           2.0            0.0          2.0           511.5        511.5
4   60585       PLAINFIELD                 911  2025-07-15              2           2.0            0.0          2.0           455.5        455.5
5   60490      BOLINGBROOK                 752  2025-07-15              2           2.0            0.0          2.0           376.0        376.0
6   60031           GURNEE                 726  2025-07-15              2           2.0            0.0          2.0           363.0        363.0
7   60402           BERWYN                 351  2025-07-15              1           0.0            1.0          1.0           351.0        351.0
8   60643          CHICAGO                 350  2025-07-15              1           1.0            0.0          1.0           350.0        350.0
9   60110  CARPENTERSVILLE                 323  2025-07-15              1           1.0            0.0          1.0           323.0        323.0

   zipcode             city  registration_count  station_count  total_ports  ev_per_port
0    60622          CHICAGO                1022              1          1.0       1022.0
1    60565       NAPERVILLE                1307              1          2.0        653.5
2    60630          CHICAGO                 550              1          1.0        550.0
3    60521         HINSDALE                1023              2          2.0        511.5
4    60585       PLAINFIELD                 911              2          2.0        455.5
5    60490      BOLINGBROOK                 752              2          2.0        376.0
6    60031           GURNEE                 726              2          2.0        363.0
7    60402           BERWYN                 351              1          1.0        351.0
8    60643          CHICAGO                 350              1          1.0        350.0
9    60110  CARPENTERSVILLE                 323              1          1.0        323.0
10   60022          GLENCOE                 641              1          2.0        320.5
11   60188     CAROL STREAM                 627              1          2.0        313.5
12   60586       PLAINFIELD                 616              1          2.0        308.0
13   60641          CHICAGO                 535              3          2.0        267.5
14   60559         WESTMONT                 517              3          2.0        258.5
15   60618          CHICAGO                1261              3          5.0        252.2
16   60046       LAKE VILLA                 487              1          2.0        243.5
17   60561           DARIEN                 486              2          2.0        243.0
18   60177      SOUTH ELGIN                 472              3          2.0        236.0
19   60516    DOWNERS GROVE                 460              1          2.0        230.0

In [41]:
import pandas as pd

sql_zip_demo_latest = """
WITH ranked AS (
  SELECT
    LPAD(TRIM(CAST(zipcode AS TEXT)), 5, '0') AS zipcode,
    total_population,
    median_hh_income,
    year,
    ROW_NUMBER() OVER (
      PARTITION BY LPAD(TRIM(CAST(zipcode AS TEXT)), 5, '0')
      ORDER BY year DESC
    ) AS rn
  FROM zip_demo_df
)
SELECT zipcode, total_population, median_hh_income, year AS demo_year
FROM ranked
WHERE rn = 1
ORDER BY zipcode;
"""

zip_demo_latest = pd.read_sql(sql_zip_demo_latest, conn)

# make sure numeric types are clean
zip_demo_latest["total_population"] = pd.to_numeric(zip_demo_latest["total_population"], errors="coerce")
zip_demo_latest["median_hh_income"] = pd.to_numeric(zip_demo_latest["median_hh_income"], errors="coerce")

print(zip_demo_latest.shape)
print(zip_demo_latest.head(10))

(1396, 4)
  zipcode  total_population  median_hh_income demo_year
0   60002             24396            109047      2023
1   60004             51884            124962      2023
2   60005             29022            100304      2023
3   60007             32485             95240      2023
4   60008             22949             96213      2023
5   60010             45970            175050      2023
6   60012             11929            147352      2023
7   60013             26503            115833      2023
8   60014             48383            104657      2023
9   60015             27720            186786      2023

C:\Users\micha\AppData\Local\Temp\ipykernel_18168\994154257.py:22: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  zip_demo_latest = pd.read_sql(sql_zip_demo_latest, conn)

In [107]:
zip_metrics_dem = (
    zip_metrics
      .merge(zip_demo_latest, on="zipcode", how="left")
)

# Helpful derived metric: EV registrations per 1,000 residents
zip_metrics_dem["ev_per_1k_pop"] = (
    zip_metrics_dem.apply(
        lambda x: (x["registration_count"] / x["total_population"] * 1000)
                  if pd.notnull(x["total_population"]) and x["total_population"] > 0
                  else None,
        axis=1
    )
)

# Quick peek
display(
    zip_metrics_dem.head(40)[
        ["zipcode","city","registration_count","station_count","total_ports",
         "ev_per_port","total_population","median_hh_income","demo_year","ev_per_1k_pop"]
    ]
)

   zipcode               city  registration_count  station_count  total_ports  ev_per_port  total_population  median_hh_income demo_year  ev_per_1k_pop
0    60622            CHICAGO                1022              1          1.0  1022.000000           53696.0          124852.0      2023      19.033075
1    60565         NAPERVILLE                1307              1          2.0   653.500000           39244.0          160238.0      2023      33.304454
2    60630            CHICAGO                 550              1          1.0   550.000000           54242.0           97134.0      2023      10.139744
3    60521           HINSDALE                1023              2          2.0   511.500000           18097.0          244318.0      2023      56.528706
4    60585         PLAINFIELD                 911              2          2.0   455.500000           24948.0          151202.0      2023      36.515953
5    60490        BOLINGBROOK                 752              2          2.0   376.000000           21739.0          148153.0      2023      34.592208
6    60031             GURNEE                 726              2          2.0   363.000000           37208.0          114008.0      2023      19.511933
7    60402             BERWYN                 351              1          1.0   351.000000           63867.0           73993.0      2023       5.495796
8    60643            CHICAGO                 350              1          1.0   350.000000           47802.0           83015.0      2023       7.321869
9    60110    CARPENTERSVILLE                 323              1          1.0   323.000000           39028.0           87714.0      2023       8.276109
10   60022            GLENCOE                 641              1          2.0   320.500000            8415.0          250001.0      2023      76.173500
11   60188       CAROL STREAM                 627              1          2.0   313.500000           42087.0          107560.0      2023      14.897712
12   60586         PLAINFIELD                 616              1          2.0   308.000000           48006.0          122963.0      2023      12.831729
13   60641            CHICAGO                 535              3          2.0   267.500000           67400.0           81649.0      2023       7.937685
14   60559           WESTMONT                 517              3          2.0   258.500000           24404.0           87474.0      2023      21.185052
15   60618            CHICAGO                1261              3          5.0   252.200000           91896.0          101558.0      2023      13.722034
16   60046         LAKE VILLA                 487              1          2.0   243.500000           34708.0          122376.0      2023      14.031347
17   60561             DARIEN                 486              2          2.0   243.000000           22975.0          109974.0      2023      21.153428
18   60177        SOUTH ELGIN                 472              3          2.0   236.000000           24030.0          123700.0      2023      19.642114
19   60516      DOWNERS GROVE                 460              1          2.0   230.000000           28594.0          118780.0      2023      16.087291
20   60510            BATAVIA                 460              2          2.0   230.000000           28577.0          120925.0      2023      16.096861
21   60302           OAK PARK                 916              2          4.0   229.000000           32589.0           97414.0      2023      28.107644
22   61821          CHAMPAIGN                 220              2          1.0   220.000000           28838.0           69284.0      2023       7.628823
23   60068         PARK RIDGE                 868              3          4.0   217.000000           39227.0          138201.0      2023      22.127616
24   60443           MATTESON                 214              1          1.0   214.000000           20606.0           93941.0      2023      10.385325
25   60047        LAKE ZURICH                1655              5          8.0   206.875000           44100.0          173043.0      2023      37.528345
26   60014       CRYSTAL LAKE                 613              7          3.0   204.333333           48383.0          104657.0      2023      12.669739
27   60448             MOKENA                 403              4          2.0   201.500000           24630.0          126483.0      2023      16.362160
28   60617            CHICAGO                 198              2          1.0   198.000000           79284.0           51237.0      2023       2.497351
29   60560          YORKVILLE                 394              3          2.0   197.000000           27798.0          112160.0      2023      14.173682
30   60615            CHICAGO                 393              1          2.0   196.500000           42752.0           62105.0      2023       9.192552
31   60083          WADSWORTH                 194              1          1.0   194.000000            9655.0          111912.0      2023      20.093216
32   60558    WESTERN SPRINGS                 381              1          2.0   190.500000           13353.0          218839.0      2023      28.532914
33   60441           LOCKPORT                 369              4          2.0   184.500000           36841.0          104271.0      2023      10.016015
34   60564         NAPERVILLE                2538              9         14.0   181.285714           47243.0          176250.0      2023      53.722245
35   60156  LAKE IN THE HILLS                 362              6          2.0   181.000000           28853.0          113491.0      2023      12.546356
36   60154        WESTCHESTER                 179              1          1.0   179.000000           16524.0          103561.0      2023      10.832728
37   60305       RIVER FOREST                 348              1          2.0   174.000000           11489.0          148711.0      2023      30.289842
38   60053       MORTON GROVE                 653              3          4.0   163.250000           24687.0          106078.0      2023      26.451169
39   60614            CHICAGO                1446              4          9.0   160.666667           70444.0          139561.0      2023      20.526943

In [105]:
from sklearn.preprocessing import MinMaxScaler

# factors we’ll include
factors = ["ev_per_port","ev_per_1k_pop","total_population","median_hh_income"]

# scale to 0–1
scaler = MinMaxScaler()
scaled = scaler.fit_transform(zip_metrics_dem[factors].fillna(0))
scaled_df = pd.DataFrame(scaled, columns=[f+"_scaled" for f in factors])

# attach back
zip_scored = pd.concat([zip_metrics_dem.reset_index(drop=True), scaled_df], axis=1)

# weights (sum to 1.0)
weights = {
    "ev_per_port_scaled": 0.45,
    "ev_per_1k_pop_scaled": 0.25,
    "total_population_scaled": 0.2,
    "median_hh_income_scaled": 0.1
}

# weighted score
zip_scored["site_score"] = (
    zip_scored["ev_per_port_scaled"] * weights["ev_per_port_scaled"] +
    zip_scored["ev_per_1k_pop_scaled"] * weights["ev_per_1k_pop_scaled"] +
    zip_scored["total_population_scaled"] * weights["total_population_scaled"] +
    zip_scored["median_hh_income_scaled"] * weights["median_hh_income_scaled"]
)

# rank results
zip_scored = zip_scored.sort_values("site_score", ascending=False)

display(zip_scored[["zipcode","city","site_score"]].head(40))

###Step 5. Interpret High score = big population + high EV adoption + underserved supply.

#60188

     zipcode               city  site_score
0      60622            CHICAGO    0.672034
1      60565         NAPERVILLE    0.501177
2      60630            CHICAGO    0.454085
3      60521           HINSDALE    0.428997
15     60618            CHICAGO    0.396343
4      60585         PLAINFIELD    0.391847
7      60402             BERWYN    0.378267
6      60031             GURNEE    0.352292
10     60022            GLENCOE    0.351736
13     60641            CHICAGO    0.351020
8      60643            CHICAGO    0.350713
5      60490        BOLINGBROOK    0.348564
12     60586         PLAINFIELD    0.339486
28     60617            CHICAGO    0.335360
11     60188       CAROL STREAM    0.333656
34     60564         NAPERVILLE    0.333417
42     60608            CHICAGO    0.328182
39     60614            CHICAGO    0.325295
9      60110    CARPENTERSVILLE    0.323962
25     60047        LAKE ZURICH    0.318690
51     60625            CHICAGO    0.317194
1539   60629            CHICAGO    0.302522
78     60804             CICERO    0.298362
123    60647            CHICAGO    0.297397
52     60016        DES PLAINES    0.296334
21     60302           OAK PARK    0.295580
102    60632            CHICAGO    0.295571
23     60068         PARK RIDGE    0.294975
26     60014       CRYSTAL LAKE    0.294325
16     60046         LAKE VILLA    0.288251
50     60004  ARLINGTON HEIGHTS    0.285928
14     60559           WESTMONT    0.284936
53     60126           ELMHURST    0.280952
135    60639            CHICAGO    0.280211
30     60615            CHICAGO    0.276218
17     60561             DARIEN    0.275460
43     60067           PALATINE    0.273755
19     60516      DOWNERS GROVE    0.273687
20     60510            BATAVIA    0.273669
86     60035      HIGHLAND PARK    0.272520

In [51]:
facility_summary = """  SELECT
  facility_type,
  COUNT(*) AS station_count,
  SUM(COALESCE(ev_level2_evse_num,0)) AS level2_ports,
  SUM(COALESCE(ev_dc_fast_count,0))   AS dc_fast_ports,
  SUM(COALESCE(ev_level2_evse_num,0)) 
    + SUM(COALESCE(ev_dc_fast_count,0)) AS total_ports
FROM il_df
WHERE status_code = 'E'
  AND (
        LOWER(COALESCE(access_code,'')) = 'public'
     OR LOWER(COALESCE(groups_with_access_code,'')) LIKE '%public%'
     OR LOWER(COALESCE(restricted_access::text,'')) = 'false'
  )
GROUP BY facility_type
ORDER BY total_ports DESC;
 """

facility_summary_df = pd.read_sql(facility_summary, conn)

# quick look
print(facility_summary_df.shape)
print(facility_summary_df.head(10))

(42, 5)
       facility_type  station_count  level2_ports  dc_fast_ports  total_ports
0               None            645        1150.0          368.0       1518.0
1    SHOPPING_CENTER             97         152.0           71.0        223.0
2              HOTEL             47         106.0            0.0        106.0
3            GROCERY             26          33.0           53.0         86.0
4         CAR_DEALER             51          64.0           12.0         76.0
5      SHOPPING_MALL             33          65.0            9.0         74.0
6            AIRPORT              8          67.0            0.0         67.0
7     PARKING_GARAGE              8          42.0            0.0         42.0
8         RESTAURANT             11          35.0            0.0         35.0
9  CONVENIENCE_STORE            395           2.0           30.0         32.0

C:\Users\micha\AppData\Local\Temp\ipykernel_18168\1709247529.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  facility_summary_df = pd.read_sql(facility_summary, conn)

In [71]:
sql_fac_zip = """  SELECT
  LPAD(TRIM(CAST(zipcode AS TEXT)), 5, '0') AS zipcode,
  facility_type,
  COUNT(*) AS station_count,
  SUM(COALESCE(ev_level2_evse_num,0)) AS level2_ports,
  SUM(COALESCE(ev_dc_fast_count,0))   AS dc_fast_ports,
  SUM(COALESCE(ev_level2_evse_num,0)) + SUM(COALESCE(ev_dc_fast_count,0)) AS total_ports
FROM il_df
WHERE status_code = 'E'
  AND (
        LOWER(COALESCE(access_code,'')) = 'public'
     OR LOWER(COALESCE(groups_with_access_code,'')) LIKE '%public%'
     OR LOWER(COALESCE(restricted_access::text,'')) = 'false'
  )
GROUP BY LPAD(TRIM(CAST(zipcode AS TEXT)), 5, '0'), facility_type
ORDER BY zipcode, total_ports DESC;
 """

fac_zip = pd.read_sql(sql_fac_zip, conn)

# replace nulls with "UNKNOWN" so they don't disappear in the pivot
fac_zip["facility_type"] = fac_zip["facility_type"].fillna("UNKNOWN")

# join with scored zips (RIGHT JOIN to keep all scored ZIPs even if no facilities)
fac_zip_scored = fac_zip.merge(
    zip_scored[["zipcode","city","site_score","ev_per_port","registration_count"]],
    on="zipcode",
    how="right"
)

# filter to top underserved (say top 20 by site_score)
top_fac_zip = fac_zip_scored.sort_values("site_score", ascending=False).head(200)

# pivot for readability: facility types as columns
matrix = top_fac_zip.pivot_table(
    index=["zipcode","city","site_score","ev_per_port","registration_count"],
    columns="facility_type",
    values="total_ports",
    aggfunc="sum",
    fill_value=0
).reset_index()

from IPython.display import display
pd.set_option("display.max_columns", None)  # show all facility type columns
display(matrix.sort_values("site_score", ascending=False).head(10))

C:\Users\micha\AppData\Local\Temp\ipykernel_18168\1588993762.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  fac_zip = pd.read_sql(sql_fac_zip, conn)

facility_type,zipcode,city,site_score,ev_per_port,registration_count,CARWASH,CAR_DEALER,COLLEGE_CAMPUS,CONVENIENCE_STORE,FLEET_GARAGE,GROCERY,HOTEL,INN,LIBRARY,OFFICE_BLDG,OTHER_ENTERTAINMENT,PARKING_LOT,PAY_GARAGE,PHARMACY,PLACE_OF_WORSHIP,RENTAL_CAR_RETURN,RESTAURANT,SCHOOL,SHOPPING_CENTER,SHOPPING_MALL,STANDALONE_STATION,UNKNOWN,UTILITY
69,60622,CHICAGO,0.672034,1022.0,1022,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
59,60565,NAPERVILLE,0.501177,653.5,1307,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
72,60630,CHICAGO,0.454085,550.0,550,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
49,60521,HINSDALE,0.428997,511.5,1023,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
68,60618,CHICAGO,0.396343,252.2,1261,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0
60,60585,PLAINFIELD,0.391847,455.5,911,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
36,60402,BERWYN,0.378267,351.0,351,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7,60031,GURNEE,0.352292,363.0,726,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
5,60022,GLENCOE,0.351736,320.5,641,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
76,60641,CHICAGO,0.351020,267.5,535,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [79]:
import folium

# center map on Illinois
m = folium.Map(location=[40.0, -89.0], zoom_start=6)

# pick a color scheme for facility types
color_map = {
    "CAR_DEALER": "red",
    "SHOPPING_CENTER": "blue",
    "SHOPPING_MALL": "purple",
    "GROCERY": "green",
    "CONVENIENCE_STORE": "orange",
    "RESTAURANT": "pink",
    "UNKNOWN": "gray"
}

# add station markers
for _, row in stations.iterrows():
    facility = row["facility_type"] if pd.notnull(row["facility_type"]) else "UNKNOWN"
    color = color_map.get(facility, "black")  # fallback color
    
    folium.CircleMarker(
        location=[row["latitude"], row["longitude"]],
        radius=4,
        popup=f"{row['station_name']} ({facility})",
        color=color,
        fill=True,
        fill_color=color,
        fill_opacity=0.7
    ).add_to(m)

m.save("stations_map.html")
from IPython.display import display
display(m)

In [93]:
import folium

# base map
m = folium.Map(location=[40, -89], zoom_start=6)

# compute centroids by averaging station coords within each ZIP
zip_centroids = stations.groupby("zipcode")[["latitude","longitude"]].mean().reset_index()

# join with scoring
zip_bubbles = zip_centroids.merge(
    zip_scored[["zipcode","city","site_score","ev_per_port","registration_count"]],
    on="zipcode", how="left"
)

# add circle markers
for _, row in zip_bubbles.iterrows():
    score = row["site_score"]
    ev_pressure = row["ev_per_port"]
    popup_text = f"ZIP: {row['zipcode']}<br>City: {row['city']}<br>Score: {score:.3f}<br>EVs/Port: {ev_pressure:.1f}"
    
    folium.CircleMarker(
        location=[row["latitude"], row["longitude"]],
        radius= max(3, min(20, ev_pressure/50)),  # scale size by EV per port
        color="red" if ev_pressure > 500 else "orange" if ev_pressure > 200 else "green",
        fill=True,
        fill_opacity=0.6,
        popup=popup_text
    ).add_to(m)

m.save("zip_bubble_map.html")
display(m)